name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Check code
        run: cargo check

      - name: Run tests
        run: cargo test

      - name: Check formatting (if rustfmt is configured)
        run: cargo fmt --check || echo "rustfmt not configured, skipping format check"

      - name: Run clippy
        run: cargo clippy -- -D warnings

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install nih-plug tools
        run: cargo install cargo-nih-plug

      - name: Build plugin
        run: cargo nih-plug bundle jeff --release
