name: Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0, v1.2.3, etc.

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-gnu

      - name: Install Windows dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-mingw-w64-x86-64

      - name: Install cargo-nih-plug
        run: cargo install --git https://github.com/robbert-vdh/nih-plug.git cargo-nih-plug

      - name: Build Linux plugin
        run: cargo nih-plug bundle jeff --release

      - name: Build Windows plugin (library only)
        run: cargo build --release --target x86_64-pc-windows-gnu

      - name: Create release bundle
        run: |
          mkdir -p release/linux
          mkdir -p release/windows
          
          # Copy Linux builds (bundled by cargo-nih-plug)
          cp -r target/bundled/jeff.vst3 release/linux/
          cp target/bundled/jeff.clap release/linux/ 2>/dev/null || true
          
          # Create Windows VST3 bundle manually
          mkdir -p release/windows/jeff.vst3/Contents/x86_64-win
          cp target/x86_64-pc-windows-gnu/release/jeff.dll release/windows/jeff.vst3/Contents/x86_64-win/jeff.vst3

      - name: Create archives
        run: |
          cd release
          tar -czf ../jeff-linux.tar.gz linux/
          zip -r ../jeff-windows.zip windows/
          tar -czf ../jeff-all-platforms.tar.gz .

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            jeff-linux.tar.gz
            jeff-windows.zip
            jeff-all-platforms.tar.gz
          generate_release_notes: true
          draft: false
          prerelease: false
          body: |
            ## Jeff Delay Plugin v${{ github.ref_name }}
            
            Simple delay effect VST3/CLAP plugin built with Rust.
            
            ### Downloads:
            - **jeff-linux.tar.gz** - Linux VST3 + CLAP
            - **jeff-windows.zip** - Windows VST3
            - **jeff-all-platforms.tar.gz** - Both platforms
            
            ### Installation:
            - **Linux**: Extract and copy jeff.vst3 to ~/.vst3/
            - **Windows**: Extract and copy jeff.vst3 to C:\Program Files\Common Files\VST3\
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
